# Activar AndroidX (OBLIGATORIO para Compose y librerías modernas)
android.useAndroidX=true
android.enableJetifier=true

# Darle más memoria a Gradle (evita errores de Java heap space)
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# Opcionales: optimizaciones de build
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
